### PR TITLE
[WIP] Remove operator specific code

### PR DESCRIPTION
**Pull request by akashshinde**
**Why**
 - To follow principle where we will have controllers in the `devconsole-operator` repo, this PR removes all operator related code from this repo.
 - There is PR(https://github.com/redhat-developer/devconsole-operator/pull/117/commits) raised to add GitSourceAnalysis controller to `devconsole-operator`.

### CODE REVIEW

**Comment by sbose78** [comment]
@MatousJobanek , but wouldn't it be hard to sync yamls across two repos ?

**Comment by sbose78** [comment]
> for this we need the orchestrating logic 

Ah ok. Which bit are you implying? Could you please the share the development workflow you have in mind :) ?

**Comment by MatousJobanek** [comment]
> but wouldn't it be hard to sync yamls across two repos ?

it's taken from the devconsole-operator, but can be easily replaced by some other file

> Could you please the share the development workflow you have in mind :) ?

https://github.com/redhat-developer/devconsole-git/blob/master/make/Makefile.dev

**Comment by corinnekrych** [comment]
@MatousJobanek I agree that the decoupling between the 2 repos atm is not ideal.
For ex, having test implementation depends on file hosted in your repo: https://github.com/redhat-developer/devconsole-operator/blob/master/pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go#L22 looks like tight coupling.

@MatousJobanek @akashshinde Would it be possible to just import your controller from https://github.com/redhat-developer/devconsole-operator/blob/master/pkg/controller/add_gitsourceanalysis.go#L4 make it point to `devconsole-git` repo and add `devconsole-git` as a dependency in devconsole-operator's Gopkg.toml file?

**Comment by akashshinde** [comment]
> Would it be possible to just import your controller from https://github.com/redhat-developer/devconsole-operator/blob/master/pkg/controller/add_gitsourceanalysis.go#L4 make it point to devconsole-git repo and add devconsole-git as a dependency in devconsole-operator's Gopkg.toml file?

@corinnekrych do you mean keeping controller in `devconsole-git` repo ?

**Comment by MatousJobanek** [comment]
it's a good point @corinnekrych. We could keep the controller inside of this repository and add it in the `devconsole-controller` repo via the init function in `add_gitsourceanalysis.go` file. Then, the only thing we would need to do when anything is changed here is to update the corresponding dependency.
Have we considered this option @sbose78?

**Comment by sbose78** [comment]
@MatousJobanek I wasn't too sure technically if that would be possible. However, if it is, it would be fantastic.

**Comment by alexeykazakov** [comment]
@corinnekrych good point! It should be pretty straight forward just to import the controller from devconsole-git.

**Comment by MatousJobanek** [comment]
> I wasn't too sure technically if that would be possible. However, if it is, it would be fantastic.

@sbose78 @alexeykazakov I've tested it locally and everything seems working fine. Theoretically, there shouldn't be any issue with it after all as the dependency manager should fetch all necessary bits.
So, if you are fine with it I will:
1. move git controllers back to `devconsole-git` repo
2. keep both files `add_gitsourceanalysis.go` and `add_gitsource.go` there in the `devconsole-operator` repo to fetch the operator logic
3. close the opened PR https://github.com/redhat-developer/devconsole-operator/pull/138 and open it in `devconsole-git` repo
4. update dependency in  `devconsole-operator` repo

**Comment by alexeykazakov** [comment]
@MatousJobanek  +1

**Comment by MatousJobanek** [comment]
ok, I've created jira for that https://jira.coreos.com/browse/ODC-610 and also first PR: https://github.com/redhat-developer/devconsole-git/pull/27
I think that we can close this PR (#25), right?

**Comment by sbose78** [comment]
Looks good @MatousJobanek .

**Comment by akashshinde** [comment]
I think we should also move GitSource to devconsole-git.

**Comment by alexeykazakov** [comment]
> I think we should also move GitSource to devconsole-git.

What do you mean? GitSource API? It's in devconsole-api. Why would we move it to devconsole-git?

**Comment by akashshinde** [comment]
@alexeykazakov I was referring to https://github.com/redhat-developer/devconsole-operator/pull/138 PR, It seems @MatousJobanek has already taken care of that in https://github.com/redhat-developer/devconsole-git/pull/27 PR.

**Pull request closed without merging**
