### PR TITLE
WIP rename project to devconsole-git

### PR DESCRIPTION
**Pull request by sbryzak**
Signed-off-by: Shane Bryzak <sbryzak@gmail.com>

### CODE REVIEW

**Comment by sbryzak** [comment]
Code is essentially freshly-generated from operator-sdk, and still needs to be cleaned up/trimmed down.

**Comment by MatousJobanek** [comment]
@sbryzak what is your plan with this PR? The repo has been already renamed but as the code still uses the old name and imports then the CI jobs are failing for the other PRs. It would be great if the overall rename process was completed. Thanks

**Comment by alexeykazakov** [comment]
I think it's easier to create a new PR rather than resolving conflicts here :)
Here is the new PR https://github.com/redhat-developer/devconsole-git/pull/22

**Pull request closed without merging**
